import { version } from "react";

const contractData = [
  {
    name: "Lottery",
    address: "0xB3...534d",
    balance: "900",
    txs: "9",
    compiler: "Solidity",
    version: "v0.8.26",
    settings: false,
    verified: "1d ago",
  },
  {
    name: "Lottery",
    address: "0xB3...534d",
    balance: "900",
    txs: "9",
    compiler: "Solidity",
    version: "v0.8.26",
    settings: false,
    verified: "1d ago",
  },
  {
    name: "Lottery",
    address: "0xB3...534d",
    balance: "900",
    txs: "9",
    compiler: "Solidity",
    version: "v0.8.26",
    settings: false,
    verified: "1d ago",
  },
  {
    name: "Lottery",
    address: "0xB3...534d",
    balance: "900",
    txs: "9",
    compiler: "Solidity",
    version: "v0.8.26",
    settings: false,
    verified: "1d ago",
  },
  {
    name: "Bridge",
    address: "0x52...F524",
    balance: "0",
    txs: "1",
    compiler: "Solidity",
    version: "v0.8.9",
    settings: true,
    verified: "3w ago",
  },
  {
    name: "Bridge",
    address: "0x52...F524",
    balance: "0",
    txs: "1",
    compiler: "Solidity",
    version: "v0.8.9",
    settings: true,
    verified: "3w ago",
  },
  {
    name: "Bridge",
    address: "0x52...F524",
    balance: "0",
    txs: "1",
    compiler: "Solidity",
    version: "v0.8.9",
    settings: true,
    verified: "3w ago",
  },
  {
    name: "Bridge",
    address: "0x52...F524",
    balance: "0",
    txs: "1",
    compiler: "Solidity",
    version: "v0.8.9",
    settings: true,
    verified: "3w ago",
  },
  {
    name: "TokenChomper",
    address: "0x...",
    balance: "399.848476",
    txs: "3",
    compiler: "Solidity",
    version: "v0.8.10",
    settings: true,
    verified: "4w ago",
  },
  {
    name: "TokenChomper",
    address: "0x...",
    balance: "399.848476",
    txs: "3",
    compiler: "Solidity",
    version: "v0.8.10",
    settings: true,
    verified: "4w ago",
  },
  {
    name: "TokenChomper",
    address: "0x...",
    balance: "399.848476",
    txs: "3",
    compiler: "Solidity",
    version: "v0.8.10",
    settings: true,
    verified: "4w ago",
  },
  {
    name: "TokenChomper",
    address: "0x...",
    balance: "399.848476",
    txs: "3",
    compiler: "Solidity",
    version: "v0.8.10",
    settings: true,
    verified: "4w ago",
  },
  {
    name: "TokenChomper",
    address: "0x...",
    balance: "399.848476",
    txs: "3",
    compiler: "Solidity",
    version: "v0.8.10",
    settings: true,
    verified: "4w ago",
  },
  {
    name: "TokenChomper",
    address: "0x...",
    balance: "399.848476",
    txs: "3",
    compiler: "Solidity",
    version: "v0.8.10",
    settings: true,
    verified: "4w ago",
  },
];

export default contractData;
