const TransactionsData= [
  
    {
      id: 1,
      contactType: "Contact Call",
      status: "Failed",
      user: "Oxbabujawufbadguwagdu....xo",
      timeAgo: "53m ago",
      details: {
        icon1: "i",
        icon2: "i",
        name: "Oxbabuj",
        icon3: "i",
      },
      heartbeatType: "Heartbeat",
      one: "0",
      fee: "0.0002",
      shard: "0",
    },
    
    {
        id: 2,
        contactType: "Token Transfer",
        status: "Success",
        user: "Oxbajfhoejfbeuwq....xo",
        timeAgo: "2h ago",
        details: {
          icon1: "i",
          icon2: "i",
          name: "Oxytbnmej",
          icon3: "i",
        },
        heartbeatType: "Pulse",
        one: "1",
        fee: "0.0004",
        shard: "2",
      },{
        id: 3,
        contactType: "Token Transfer",
        status: "Success",
        user: "Oxbajfhoejfbeuwq....xo",
        timeAgo: "2h ago",
        details: {
          icon1: "i",
          icon2: "i",
          name: "Oxytbnmej",
          icon3: "i",
        },
        heartbeatType: "Pulse",
        one: "1",
        fee: "0.0004",
        shard: "2",
      },{
        id: 4,
        contactType: "Token Transfer",
        status: "Success",
        user: "Oxbajfhoejfbeuwq....xo",
        timeAgo: "2h ago",
        details: {
          icon1: "i",
          icon2: "i",
          name: "Oxytbnmej",
          icon3: "i",
        },
        heartbeatType: "Pulse",
        one: "1",
        fee: "0.0004",
        shard: "2",
      },{
        id: 5,
        contactType: "Token Transfer",
        status: "Success",
        user: "Oxbajfhoejfbeuwq....xo",
        timeAgo: "2h ago",
        details: {
          icon1: "i",
          icon2: "i",
          name: "Oxytbnmej",
          icon3: "i",
        },
        heartbeatType: "Pulse",
        one: "1",
        fee: "0.0004",
        shard: "2",
      },{
        id: 6,
        contactType: "Token Transfer",
        status: "Success",
        user: "Oxbajfhoejfbeuwq....xo",
        timeAgo: "2h ago",
        details: {
          icon1: "i",
          icon2: "i",
          name: "Oxytbnmej",
          icon3: "i",
        },
        heartbeatType: "Pulse",
        one: "1",
        fee: "0.0004",
        shard: "2",
      },{
        id: 7,
        contactType: "Token Transfer",
        status: "Success",
        user: "Oxbajfhoejfbeuwq....xo",
        timeAgo: "2h ago",
        details: {
          icon1: "i",
          icon2: "i",
          name: "Oxytbnmej",
          icon3: "i",
        },
        heartbeatType: "Pulse",
        one: "1",
        fee: "0.0004",
        shard: "2",
      },
    // Add more entries as needed
  ];

  export default TransactionsData